# Generated by Django 5.2.13 on 2026-04-30 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_newsblog', '0021_remove_article_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectCategories',
            fields=[
                ('newsblogcategoriesplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aldryn_newsblog.newsblogcategoriesplugin')),
                ('label', models.CharField(blank=True, max_length=255, null=True, verbose_name='Label')),
                ('first_option_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Text of the first empty item')),
            ],
            options={
                'abstract': False,
            },
            bases=('aldryn_newsblog.newsblogcategoriesplugin',),
        ),
        migrations.CreateModel(
            name='SelectYear',
            fields=[
                ('newsblogarchiveplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aldryn_newsblog.newsblogarchiveplugin')),
                ('label', models.CharField(blank=True, max_length=255, null=True, verbose_name='Label')),
                ('first_option_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Text of the first empty item')),
            ],
            options={
                'abstract': False,
            },
            bases=('aldryn_newsblog.newsblogarchiveplugin',),
        ),
    ]
