# Generated by Django 5.2.13 on 2026-04-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aldryn_newsblog", "0021_remove_article_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsblogarchiveplugin",
            name="template_list",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Template list"
            ),
        ),
        migrations.AddField(
            model_name="newsblogarticlesearchplugin",
            name="template_list",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Template list"
            ),
        ),
        migrations.AddField(
            model_name="newsblogauthorsplugin",
            name="template_list",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Template list"
            ),
        ),
        migrations.AddField(
            model_name="newsblogcategoriesplugin",
            name="template_list",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Template list"
            ),
        ),
        migrations.AddField(
            model_name="newsblogfeaturedarticlesplugin",
            name="template_list",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Template list"
            ),
        ),
        migrations.AddField(
            model_name="newsbloglatestarticlesplugin",
            name="template_list",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Template list"
            ),
        ),
        migrations.AddField(
            model_name="newsblogtagsplugin",
            name="template_list",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Template list"
            ),
        ),
    ]
