# Generated by Django 6.0.7 on 2026-07-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aldryn_newsblog", "0022_selectcategories_selectyear"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="articletranslation",
            unique_together={("language_code", "slug")},
        ),
        migrations.AlterUniqueTogether(
            name="newsblogconfigtranslation",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="newsblogconfig",
            name="placeholder_base_sidebar",
        ),
        migrations.RemoveField(
            model_name="newsblogconfig",
            name="placeholder_base_top",
        ),
        migrations.RemoveField(
            model_name="newsblogconfig",
            name="placeholder_detail_bottom",
        ),
        migrations.RemoveField(
            model_name="newsblogconfig",
            name="placeholder_detail_footer",
        ),
        migrations.RemoveField(
            model_name="newsblogconfig",
            name="placeholder_detail_top",
        ),
        migrations.RemoveField(
            model_name="newsblogconfig",
            name="placeholder_list_footer",
        ),
        migrations.RemoveField(
            model_name="newsblogconfig",
            name="placeholder_list_top",
        ),
        migrations.AddConstraint(
            model_name="articletranslation",
            constraint=models.UniqueConstraint(
                fields=("language_code", "master"),
                name="aldryn_newsblog_article_translation_uniq_lang",
            ),
        ),
        migrations.AddConstraint(
            model_name="newsblogconfigtranslation",
            constraint=models.UniqueConstraint(
                fields=("language_code", "master"),
                name="aldryn_newsblog_newsblogconfig_translation_uniq_lang",
            ),
        ),
    ]
