# Generated by Django 6.1.1 on 2026-09-15 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aldryn_newsblog", "0023_alter_articletranslation_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleWithRelated",
            fields=[],
            options={
                "verbose_name": "Article + related articles",
                "verbose_name_plural": "Articles + related articles",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("aldryn_newsblog.article",),
        ),
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["-publishing_date"],
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
            },
        ),
        migrations.AlterModelOptions(
            name="articletranslation",
            options={
                "default_permissions": (),
                "managed": True,
                "verbose_name": "Article Translation",
            },
        ),
    ]
