# Generated by Django 6.1.1 on 2026-09-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aldryn_newsblog", "0023_alter_articletranslation_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsblogfeaturedarticlesplugin",
            name="select_only_current_language",
            field=models.BooleanField(
                default=False, help_text="Select only the current language version."
            ),
        ),
        migrations.AddField(
            model_name="newsbloglatestarticlesplugin",
            name="select_only_current_language",
            field=models.BooleanField(
                default=False, help_text="Select only the current language version."
            ),
        ),
        migrations.AddField(
            model_name="newsblogrelatedplugin",
            name="select_only_current_language",
            field=models.BooleanField(
                default=False, help_text="Select only the current language version."
            ),
        ),
    ]
